# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DeBank' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DeBank
  pod 'Firebase/Core', '~> 6.2.0'
  pod 'Firebase/Messaging', '~> 6.2.0'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  target 'DeBankTests' do
    inherit! :search_paths
    # Pods for testing
  end

  system("mkdir -p Pods/Headers/Public/FirebaseCore && cp Pods/FirebaseCore/Firebase/Core/Public/* Pods/Headers/Public/FirebaseCore/")

end
