# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'DeBank' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for DeBank
  pod 'Firebase/Core'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'lottie-ios', :path => '../node_modules/lottie-ios'

  pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'

  target 'DeBankTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'DeBank-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for DeBank-tvOS

  target 'DeBank-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
